name: Unit Tests
description: 'Performs unit tests'

inputs:
  java_version:
    description: 'The version of Java to use'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - uses: actions/setup-java@v3.5.1
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java_version }}
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test jacocoTestReport --stacktrace
