name: Unit Tests
description: 'Performs unit tests'

inputs:
  java_version:
    description: 'The version of Java to use'
    required: true

runs:
  using: composite
  steps:
    - name: Java Setup
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java_version }}
    - name: Gradle Test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test --stacktrace
