name: Publish
description: 'Publish to Sonatype'

inputs:
  java_version:
    description: 'The version of java to use'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java_version }}
    - name: Publish
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publishAllPublicationsToMavenCentral --no-daemon --no-parallel
