name: Determine Version
description: 'Analyzes commits and github releases to calculate version'

inputs:
  node_version:
    description: 'The version of nodejs to use'
    required: true
  semantic_release_version:
    description: 'The version of semantic release to use'
    required: true
  conventional_changelog_version:
    description: 'The version of conventional changelog to use'
    required: true

outputs:
  releaseType:
    description: "Semantic type, e.g. major, minor, patch"
    value: ${{ steps.dv.outputs.RELEASE_TYPE }}
  releaseChannel:
    description: "Stable or Pre-release"
    value: ${{ steps.dv.outputs.RELEASE_CHANNEL }}
  buildVersion:
    description: "The calculated version"
    value: ${{ steps.dv.outputs.BUILD_VERSION }}

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ inputs.node_version }}
    - name: Install Semantic Release
      shell: bash
      run: npm install -g semantic-release@${{ inputs.semantic_release_version }} conventional-changelog-conventionalcommits@${{ inputs.conventional_changelog_version }}
    - name: Configure Semantic Release
      shell: bash
      run: |
        CONFIG_SEMANTIC_RELEASE=$(cat << JSON
          {
            "plugins": [
              ["@semantic-release/commit-analyzer", {
                "preset": "conventionalcommits"
              }]
            ],
            "branches": [
              "+([0-9])?(.{+([0-9]),x}).x",
              "main",
              {
                "name": "beta",
                "prerelease": true
              },
              {
                "name": "alpha",
                "prerelease": true
              }
            ]
          }
        JSON
        )
        echo $CONFIG_SEMANTIC_RELEASE > .releaserc.json
    - name: Determine Version
      id: dv
      shell: bash
      run: |
        SEM_RELEASE="$(semantic-release --dry-run || true)"
        NEXT_VERSION=$(echo "$SEM_RELEASE" | (grep 'next release version is' || true) | sed -n -e 's/.*next release version is //p')
        if [ -z "$NEXT_VERSION" ];
          then
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 2> /dev/null || echo "v0.0.1")
            BUILD_VERSION="${PREVIOUS_TAG:1}"
          else
            BUILD_VERSION=$NEXT_VERSION
        fi
        NEXT_RELEASE_TYPE=$(echo "$SEM_RELEASE" | (grep 'commits complete' || true) | sed 's/.*complete. \(.*\) release/\1/')
        if [[ "$NEXT_RELEASE_TYPE" == "no" ]]
          then RELEASE_TYPE=""
          else RELEASE_TYPE=$NEXT_RELEASE_TYPE
        fi
        NEXT_RELEASE_CHANNEL=$(echo "$SEM_RELEASE" | (grep 'Published release' || true) | sed 's/.*on \(.*\) channel/\1/')
        if [[ -z "$NEXT_RELEASE_CHANNEL" ]];
          then RELEASE_CHANNEL="";
          else RELEASE_CHANNEL=$NEXT_RELEASE_CHANNEL;
        fi
        echo "Release Type: $RELEASE_TYPE"
        echo "Release Channel: $RELEASE_CHANNEL"
        echo "Build Version: $BUILD_VERSION"
        echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_OUTPUT
        echo "RELEASE_CHANNEL=$RELEASE_CHANNEL" >> $GITHUB_OUTPUT
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_OUTPUT
        echo "# Determine Version Output" >> $GITHUB_STEP_SUMMARY
        echo "- Type: $RELEASE_TYPE" >> $GITHUB_STEP_SUMMARY
        echo "- Channel: $RELEASE_CHANNEL" >> $GITHUB_STEP_SUMMARY
        echo "- Version: $BUILD_VERSION" >> $GITHUB_STEP_SUMMARY
